name: Build and Test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Publish to npm 
      run: npm publish --registry https://www.npmjs.com/settings/capregsoft/packages --tag latest
      env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}