on: push
name: Publish package
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish package
      run: npm publish --registry https://www.npmjs.com/settings/capregsoft/packages --tag latest
